### ISSUE TITLE
Support for Angular Material Components?

### ISSUE THREAD

**Issue by nadelbaeumchen** [South-Paw/storybook-addon-overview-angular#23] opened 2019-09-17 13:19 UTC
Hi,

I'm sorry if this is the wrong place to ask.
I'm currently working on a Storybook that shows not only documentation for our own custom components but also for Angular Material Components that we use. Our problem is that overview requires a filename or a component file but since we are using the Material Components, we do not have such files (at least not that I know).

Can someone help me getting the Overview addon to work with Material Components?

Thank you in advance.

**Comment by rheimus** [comment] 2019-09-17 22:11
You are probably going to run into a larger problem of needing typedoc generation of Material components.

The file name is just being used as an identifier for the typedoc if I recall correctly.

**Comment by South-Paw** [comment] 2019-09-17 22:12
Before you can document them using this addon you'd first need to configure the typedoc package/script to include the components (in this case, the material ones) so it generates typedocs for them - without these you can't move forward.

The `filename` in the addon's per story config is just a unique id that typedoc has in its objects and it matches the component src that you're loading into the Storybook addon.

So once they're in your typedoc, you can hunt down the correct `filename` to load them with.

Note that at the very least you probably wont get descriptions or annotations for any of the properties of the angular material components because you'll be typedoc'ing compiled/generated code rather than the source - other things may not work either.

Please take note that while this is all possible to do with this addon (as I've described above) it may not work as you expect.

You're essentially just reproducing some documentation for what is (I assume) already documented on the angular material project website. You should consider just linking out to their docs for the components you use rather than investing all this time into reproducing it.

I'm going to close this as it's not an issue or bug with the repo, feel free to discuss further on here though.

**Closed as completed by South-Paw** 2019-09-17 22:12 UTC
Labels: question
