### ISSUE TITLE
Add support for documenting class properties and methods

### ISSUE THREAD

**Issue by TheSonOfThomp** [South-Paw/storybook-addon-overview-angular#11] opened 2019-04-25 16:10 UTC
Sometimes you may want to document class attributes for a component, directive, module or service (particularly for services associated with storybook components i.e. `MyIconRegistry`)

Adding support for something like this may be useful.
> ## Properties
> `className`:  `get` `string`
> 
> The class name applied to the DOM element

**Comment by TheSonOfThomp** [comment] 2019-04-25 19:25
Initial PR #12

**Comment by South-Paw** [comment] 2019-06-03 04:59
Duplicate of #6

**Comment by South-Paw** [comment] 2019-06-03 05:01
Wait. I don't know why I thought this was a duplicate... sorry.

**Closed as completed** 2019-06-19 05:08 UTC
Labels: enhancement
